# These are supported funding model platforms

github: ikegami-yukino
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://github.com/ikegami-yukino', 'https://ikegami-yukino.github.io/']
